version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt install nodejs \
            npm --version
            npm install -g csslint
  css-style:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: |
          csslint src/css/style.css
          echo "did this work like I thought it would?"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  css-build-and-test:
    jobs:
      - build
      - css-style
